added docker cicd template
CSUN-IT/.github pull request #1
Opened 2020-09-30 19:38 UTC by petersin0422

2020-09-30 21:27 UTC, allejo requested changes
- Can you rename `docker-build.yaml` to `docker-publish.yaml`?
- Also, can you see if we can push to the GitHub Container Registry instead? I don't think there's a point in introducing a deprecated service in a template

2020-09-30 21:27 UTC, allejo commented on workflow-templates/docker-build.yaml
> +          RELEASE_VERSION=$(echo $(echo ${GITHUB_REF:10} | tr '[:upper:]' '[:lower:]'))
```suggestion
          RELEASE_VERSION=$(echo ${GITHUB_REF:10} | tr '[:upper:]' '[:lower:]')
```

2020-09-30 21:27 UTC, allejo commented on workflow-templates/docker-build.yaml
> +          APPLICATION_NAME=${GITHUB_REPOSITORY,,}
```suggestion
          APPLICATION_NAME=${GITHUB_REPOSITORY,,} # convert repo name to lowercase
```

Since this can be used by more people, we should explain weird syntax just in case

2020-09-30 21:27 UTC, allejo commented on workflow-templates/docker-build.yaml
> +            ${{ env.DOCKER_REGISTRY }}/${{ env.APPLICATION_NAME }}:latest
I do not see where you're specifying the credentials for authenticating to GitHub Packages or container registry. Shouldn't that be here somewhere?

2020-09-30 21:27 UTC, allejo commented on workflow-templates/docker-ci.yaml
> +          APPLICATION_NAME=${GITHUB_REPOSITORY,,}
```suggestion
          APPLICATION_NAME=${GITHUB_REPOSITORY,,} # convert repo name to lowercase
```

2020-09-30 21:27 UTC, allejo commented on workflow-templates/docker-ci.yaml
> +name: DockerCI
```suggestion
name: Docker Security Scan
```

2020-09-30 21:27 UTC, allejo commented on workflow-templates/docker-build.yaml
> +      - master
```suggestion
```

We don't want this to happen on master. This would create an image with the Docker tag of `master` probably, which I don't think we want.

2020-09-30 21:27 UTC, allejo commented on workflow-templates/docker-ci.yaml
> +  build-and-scan-image:
```suggestion
  build-and-trivy-scan:
```

In case we add more security-related jobs

2020-09-30 22:25 UTC, petersin0422 commented on workflow-templates/docker-build.yaml
> +          APPLICATION_NAME=${GITHUB_REPOSITORY,,}
maybe just stop using BASH?

2020-09-30 22:54 UTC, petersin0422 commented on workflow-templates/docker-build.yaml
> +            ${{ env.DOCKER_REGISTRY }}/${{ env.APPLICATION_NAME }}:latest
> * Also, can you see if we can push to the GitHub Container Registry instead? I don't think there's a point in introducing a deprecated service in a template

Currently, GitHub Container Registry is in beta and [only supports PAT](https://docs.github.com/en/free-pro-team@latest/packages/getting-started-with-github-container-registry/migrating-to-github-container-registry-for-docker-images#authenticating-with-the-container-registry). Let's wait a bit and see if that will change.

2020-10-01 16:55 UTC, allejo approved these changes

2020-10-01 16:55 UTC, merged