Add slash command template for '/tag' support
CSUN-IT/.github pull request #6
Opened 2020-12-23 06:09 UTC by ChristopherHaklar

Fixes #2

2021-01-04 20:31 UTC, allejo requested changes

2021-01-04 20:31 UTC, allejo commented on workflow-templates/slash-command-tag.yaml
> +  job1:
```suggestion
  slash_command:
```

2021-01-04 20:31 UTC, allejo commented on workflow-templates/slash-command-tag.yaml
> +          echo "Comment on PR #${{ github.event.issue.number }}"
should this `if` be moved outside the `steps` and under the actual job instead? That way this job entirely doesn't run instead of just this step

2021-01-04 20:31 UTC, allejo commented on workflow-templates/slash-command-tag.yaml
> +          permission-level: none
```suggestion
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command: tag
          reaction: true
          reaction-type: "hooray"
          allow-edits: false
          permission-level: write
```

- For boolean values in YAML, let's not have them in quotes. Unless this action itself requires them to be strings?
- Let's try setting the permission-level to ppl with write access

2021-01-04 20:31 UTC, allejo commented on workflow-templates/slash-command-tag.yaml
> +        id: create_release
- We don't need an `id` here, do we?
- What's the purpose of `success()` here? Wouldn't this be assumed? i.e. this step wouldn't be reached if a previous step failed

2021-01-04 22:01 UTC, ChristopherHaklar commented on workflow-templates/slash-command-tag.yaml
> +          echo "Comment on PR #${{ github.event.issue.number }}"
Can we move it outside of a step like that? If so I think that would be the right way to do it.

2021-01-04 22:04 UTC, ChristopherHaklar commented on workflow-templates/slash-command-tag.yaml
> +          permission-level: none
- I do think the repo we are using for this (xt0rted/slash-command-action@v1) does require them to be strings but I can do a test run without the quotes first if you want me to.
- For the permission level, I will change it but it also wouldn't complete the PR even if someone triggers the action if they themselves don't have the ability to commit the PR, so it's safe with 'none' there too afaik.

2021-01-04 22:07 UTC, ChristopherHaklar commented on workflow-templates/slash-command-tag.yaml
> +        id: create_release
- Don't think so no, probably just leftover from a template
- Steps will still continue even if the previous one fails, no? That's why I added this to ensure that every step had completed correctly and none had been cancelled before making a release.

2021-01-04 22:49 UTC, allejo commented on workflow-templates/slash-command-tag.yaml
> +          echo "Comment on PR #${{ github.event.issue.number }}"
I believe so, there is [`jobs.<job_id>.if`](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idif)

2021-01-04 22:57 UTC, allejo commented on workflow-templates/slash-command-tag.yaml
> +        id: create_release
Unless you have steps that rely on `always()` or `failure()`, the first step that fails will stop all further steps from running.

2021-01-04 23:01 UTC, allejo commented on workflow-templates/slash-command-tag.yaml
> +          permission-level: none
- Could you try using boolean values in dev-null. If this action _does_ require strings, can you add a comment explaining that the action requires it. We wouldn't want someone in the future to be confused
- Is that so? The token we're using for merging is `GITHUB_TOKEN` so that token would have access to merging even if the person who has read-only access to the repo triggers it, right?

2021-01-04 23:52 UTC, ChristopherHaklar commented on workflow-templates/slash-command-tag.yaml
> +          permission-level: none
- Looks like it worked without the ""
- And it still logs who started the action, even if it was indirectly, so it shouldn't be able to do anything beyond their permissions but I'll change it to "write" instead of "none"

2021-01-04 23:53 UTC, ChristopherHaklar commented on workflow-templates/slash-command-tag.yaml
> +        id: create_release
Yup, you were right, commented them out and tested it looks like it works

2021-01-05 19:40 UTC, allejo commented
I was going to throw this your way but decided I wouldn't torment you any longer with this. I made commit 0d6f62d7158a4c5297169786d58e94bfb93ecb80.

Basically, the `actions/create-release` action will create a tag/release on the default branch for the repo. Most of the time, that branch for us is `develop`. However, we don't usually create tags on the `develop` branch and instead use `master` or `MAJOR.MINOR` for that. So we needed to make sure the tag is being created off the branch that the PR is merging _into_.

Since there's no way to know the target branch for a PR from an `issue_comment` event, we use another action ([`octokit/request-action`](https://github.com/octokit/request-action)) to query the GitHub API to know what is the target branch for said PR and then use that as the `commitish` value for `actions/create-release`.

2021-01-05 19:41 UTC, allejo approved these changes
thank you for this :smile:

squash+merge pls

2021-01-05 22:50 UTC, merged